### ISSUE TITLE
menu burger accueil

### ISSUE THREAD

**Issue by Nicolas-Montard** [WildCodeSchool/2022-09-php-remote-p2-where-is-my-band#42]
Sur la page d'accueil, pendant que le menu burger s'ouvre, les informations du menu burger se déploie a gauche de la page d'accueil, mais se colle a droite une fois pleinement déployé.

**Comment by jfm-wcs** [comment]
@Nicolas-Montard en effet et pour compléter ta remarque, une fois sur la page `/results`, le menu déroulé passe derrière les cards des groupes en mode mobile 😉

**Comment by marinevlrg** [comment]
c'est ok :)
