### ISSUE TITLE
Contacter un groupe

### ISSUE THREAD

**Issue by jfm-wcs** [WildCodeSchool/2022-09-php-remote-p2-where-is-my-band#43]
C'est étrange, lorsque je clique sur `contacter le groupe`, je suis redirigé sur un formulaire mais je ne vois plus à quel groupe j'envoie mon message. 
Je voulais contacter Nirvana mais j'ai peur que mon message arrive chez Metallica 🥶

**Comment by Axl-Crz** [comment]
Good aussi
